baseURL: 'https://louiscklaw.github.io/'
title: louis portfolio
paginate: 99
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-JNL4SDHMH8

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: louis portfolio
  description: 'louis portfolio'
  keywords:
    [
      louislabs,
      Blog,
      Portfolio,
      validation engineer,
      developer,
      testing engineer,
      github,
    ]
  author: louis
  # author: ["Me", "You"] # multiple authors
  images: ['https://avatars.githubusercontent.com/u/1376093?v=4']
  DateFormat: 'January 2, 2006'
  defaultTheme: light # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: 'https://avatars.githubusercontent.com/u/1376093?v=4'
    favicon16x16: 'https://avatars.githubusercontent.com/u/1376093?v=4'
    favicon32x32: 'https://avatars.githubusercontent.com/u/1376093?v=4'
    apple_touch_icon: 'https://avatars.githubusercontent.com/u/1376093?v=4'
    safari_pinned_tab: 'https://avatars.githubusercontent.com/u/1376093?v=4'

  label:
    text: 'louiscklaw'
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Hi, I am louis
    subtitle: 'a validation engineer'
    imageUrl: 'https://avatars.githubusercontent.com/u/1376093?v=4'
    imageWidth: 120
    imageHeight: 120
    imageTitle: My PiC

    buttons:
      - name: works
        url: works

      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog, I'm louis, a validation engineer

  socialIcons:
    - name: linkedin
      url: 'https://www.linkedin.com/in/louiscklaw'

    - name: github
      url: 'https://github.com/louiscklaw'

    - name: slack
      url: 'https://louislabs.slack.com/messages/general'

    - name: telegram
      url: 'https://t.me/louiscklaw'

    - name: keybase
      url: 'https://keybase.io/louiscklaw'

  analytics:
    google:
      SiteVerificationTag: 'CTFS - Security Blog | Hacking | Malware Analysis'
    bing:
      SiteVerificationTag: 'CTFS - Security Blog | Hacking | Malware Analysis'
    yandex:
      SiteVerificationTag: 'CTFS - Security Blog | Hacking | Malware Analysis'

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ['title', 'permalink', 'summary', 'content']

menu:
  main:
    - identifier: works
      name: works
      url: /works/
      weight: 10

    - identifier: about
      name: about
      url: /about/
      weight: 20

    - identifier: tags
      name: tags
      url: /tags/
      weight: 30

    - identifier: credits
      name: credits
      url: /credits/
      weight: 30

    - identifier: notes
      name: notes
      url: /notes/
      weight: 40

    - identifier: logseq
      name: logseq
      url: https://louiscklaw.github.io/logseq-helloworld/
      weight: 50

    - identifier: search
      name: search
      url: /search/
      weight: 90

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai

  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

security:
  funcs:
    getenv:
      - HOME
      - HOSTNAME
      - ^HUGO_
      - ^WC_
      - GITHUB_RUN_ID
      - WHATSAPP_NUMBER