# CREDIT: https://github.com/shren207/nextjs-docker-compose
services:
  test:
    build: .
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ../app:/app
      - node_modules:/app/node_modules
    working_dir: /app

    command: sleep infinity

volumes:
  node_modules:
